[package]
name = "mango-example-support"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
mango-core = { path = "../../../crates/kernel/core" }
mango-runtime-support = { path = "../../../crates/kernel/runtime-support" }
mango-shim-inmemory = { path = "../../../crates/substrate/inmemory-bus" }
tokio = { version = "1", features = ["rt"] }
