[package]
name = "mango-example-support"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
mango-core = { path = "../../crates/mango-core" }
mango-runtime-support = { path = "../../crates/mango-runtime-support" }
mango-shim-inmemory = { path = "../../crates/mango-shim-inmemory" }
tokio = { version = "1", features = ["rt"] }
